export enum Genre {
  Rock = "Rock",
  Pop = "Pop",
  Jazz = "Jazz",
  Classical = "Classical",
  HipHop = "HipHop",
  Country = "Country",
  Electronic = "Electronic",
  Reggae = "Reggae",
  Blues = "Blues",
  Soul = "Soul",
  Funk = "Funk",
  Disco = "Disco",
  Metal = "Metal",
  Punk = "Punk",
  Folk = "Folk",
  Indie = "Indie",
  Alternative = "Alternative",
  RnB = "RnB",
  Latin = "Latin",
  World = "World",
  Gospel = "Gospel",
  Soundtrack = "Soundtrack",
  KPop = "KPop",
  JPop = "JPop",
}
